[ElasticSearch] Init bundle
Lakion/SyliusElasticSearchBundle pull request #6
Opened 2016-12-14 16:17 UTC by Arminek

2016-12-14 18:04 UTC, pjedrzejewski requested changes

2016-12-14 18:04 UTC, pjedrzejewski commented on src/LakionSyliusElasticSearchBundle.php
> +        return [SyliusResourceBundle::DRIVER_DOCTRINE_ORM];
Not really! :) We won't support drivers other than ORM + ElasticSearch.

2016-12-14 18:04 UTC, pjedrzejewski commented on composer.json
> +        "doctrine/phpcr-odm": "^2.0@dev",
Why?

2016-12-14 18:04 UTC, pjedrzejewski commented on composer.json
> +        "jackalope/jackalope-doctrine-dbal": "^1.2",
Don't think so. :)

2016-12-14 18:04 UTC, pjedrzejewski commented on .travis.yml
> +    - src/Tests/Application/bin/console doctrine:phpcr:repository:init --env=test -vvv --no-interaction
;)

2016-12-15 09:32 UTC, merged

2016-12-15 09:33 UTC, pjedrzejewski commented
Thank you Arek!

2016-12-15 10:31 UTC, pamil commented on src/DependencyInjection/LakionSyliusElasticSearchExtension.php
> +final class LakionSyliusElasticSearchExtension extends AbstractResourceExtension
I guess this extension does not need to extend `AbstractResourceExtension`.

2016-12-15 10:31 UTC, pamil commented on src/LakionSyliusElasticSearchBundle.php
> +final class LakionSyliusElasticSearchBundle extends AbstractResourceBundle
This bundle does not need to extend `AbstractResourceBundle`.

2016-12-15 10:31 UTC, pamil commented on src/Tests/Application/app/AppKernel.php
> +            new \Lakion\SyliusElasticSearchBundle\LakionSyliusElasticSearchBundle(),
It probably can be placed together with other bundles, no need to include it as the first bundle.

2016-12-15 10:31 UTC, pamil commented on src/Tests/Application/app/config/config.yml
> +        - doctrine/orm
Is it really needed?

2016-12-15 10:31 UTC, pamil commented on src/Tests/Application/app/config/config.yml
> +        - doctrine/orm
Is it really needed?